feat(deps): bump dagger from 2.56.1 to 2.56.2 (#601)
Bumps `dagger` from 2.56.1 to 2.56.2.
Updates `com.google.dagger:hilt-compiler` from 2.56.1 to 2.56.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/google/dagger/releases">com.google.dagger:hilt-compiler's
releases</a>.</em></p>
<blockquote>
<h2>Dagger 2.56.2</h2>
<h1>Bug fixes</h1>
<ul>
<li>[Dagger] Fixes <a
href="https://redirect.github.com/google/dagger/issues/4676">#4676</a>:
Fixes <code>IndexOutOfBoundException</code> when returning
<code>suspend</code> from <code>@Provides</code> method.
(5d59aedd1)</li>
<li>[Dagger] Fixes <a
href="https://redirect.github.com/google/dagger/issues/4658">#4658</a>:
Fixes <code>NoSuchMethodError</code> due to incorrect Guava runtime
(Dagger’s Guava version is now temporarily pinned to 33.0.0 to avoid the
issue). (9fc3df48e)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/google/dagger/commit/cb98d977e8407363d90eba2fd78a088a1d7640f7"><code>cb98d97</code></a>
2.56.2 release</li>
<li><a
href="https://github.com/google/dagger/commit/96e755c0ef64b7e1c3bd592348d02c562f9d2f26"><code>96e755c</code></a>
[XPoet Migration]: Migrate ParameterSpec to XParameterSpec.</li>
<li><a
href="https://github.com/google/dagger/commit/cccec89061114a97fdbcb566ca2b1da185b15dad"><code>cccec89</code></a>
[XPoet Migration]: Migrate FieldSpec to XPropertySpec.</li>
<li><a
href="https://github.com/google/dagger/commit/5d59aedd1ca559cd42f51fb03c7ed3fa3e3b53dd"><code>5d59aed</code></a>
Disable ad-hoc support for type-use nullability on generated jave type
argume...</li>
<li><a
href="https://github.com/google/dagger/commit/9fc3df48ee8170b4b13366f7b862ecd93bc58471"><code>9fc3df4</code></a>
Pin Guava to version 33.0.0 specified in MODULE.bazel.</li>
<li><a
href="https://github.com/google/dagger/commit/b3ba9b3924bc7fb3fef5efd7abef85018645c58e"><code>b3ba9b3</code></a>
Add maven install lock file.</li>
<li><a
href="https://github.com/google/dagger/commit/7a92bc8b4a87b7ab7c345fd4bf3b6be7c12249db"><code>7a92bc8</code></a>
Internal changes</li>
<li><a
href="https://github.com/google/dagger/commit/dc3a8b32ba3d22666b5fb67b1412cd4100fa12f5"><code>dc3a8b3</code></a>
[XPoet Migration]: Migrate all MethodSpec to XFunSpec.</li>
<li><a
href="https://github.com/google/dagger/commit/9d2fda15abef318f2d41eeaddef3c2ce0308fb30"><code>9d2fda1</code></a>
Automated Code Change</li>
<li><a
href="https://github.com/google/dagger/commit/592ff20c735968fc62600bb2ac67bf35d3416261"><code>592ff20</code></a>
[XPoet Migration]: Migrate remaining TypeSpec to XTypeSpec.</li>
<li>Additional commits viewable in <a
href="https://github.com/google/dagger/compare/dagger-2.56.1...dagger-2.56.2">compare
view</a></li>
</ul>
</details>
<br />

Updates `com.google.dagger:hilt-android` from 2.56.1 to 2.56.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/google/dagger/releases">com.google.dagger:hilt-android's
releases</a>.</em></p>
<blockquote>
<h2>Dagger 2.56.2</h2>
<h1>Bug fixes</h1>
<ul>
<li>[Dagger] Fixes <a
href="https://redirect.github.com/google/dagger/issues/4676">#4676</a>:
Fixes <code>IndexOutOfBoundException</code> when returning
<code>suspend</code> from <code>@Provides</code> method.
(5d59aedd1)</li>
<li>[Dagger] Fixes <a
href="https://redirect.github.com/google/dagger/issues/4658">#4658</a>:
Fixes <code>NoSuchMethodError</code> due to incorrect Guava runtime
(Dagger’s Guava version is now temporarily pinned to 33.0.0 to avoid the
issue). (9fc3df48e)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/google/dagger/commit/cb98d977e8407363d90eba2fd78a088a1d7640f7"><code>cb98d97</code></a>
2.56.2 release</li>
<li><a
href="https://github.com/google/dagger/commit/96e755c0ef64b7e1c3bd592348d02c562f9d2f26"><code>96e755c</code></a>
[XPoet Migration]: Migrate ParameterSpec to XParameterSpec.</li>
<li><a
href="https://github.com/google/dagger/commit/cccec89061114a97fdbcb566ca2b1da185b15dad"><code>cccec89</code></a>
[XPoet Migration]: Migrate FieldSpec to XPropertySpec.</li>
<li><a
href="https://github.com/google/dagger/commit/5d59aedd1ca559cd42f51fb03c7ed3fa3e3b53dd"><code>5d59aed</code></a>
Disable ad-hoc support for type-use nullability on generated jave type
argume...</li>
<li><a
href="https://github.com/google/dagger/commit/9fc3df48ee8170b4b13366f7b862ecd93bc58471"><code>9fc3df4</code></a>
Pin Guava to version 33.0.0 specified in MODULE.bazel.</li>
<li><a
href="https://github.com/google/dagger/commit/b3ba9b3924bc7fb3fef5efd7abef85018645c58e"><code>b3ba9b3</code></a>
Add maven install lock file.</li>
<li><a
href="https://github.com/google/dagger/commit/7a92bc8b4a87b7ab7c345fd4bf3b6be7c12249db"><code>7a92bc8</code></a>
Internal changes</li>
<li><a
href="https://github.com/google/dagger/commit/dc3a8b32ba3d22666b5fb67b1412cd4100fa12f5"><code>dc3a8b3</code></a>
[XPoet Migration]: Migrate all MethodSpec to XFunSpec.</li>
<li><a
href="https://github.com/google/dagger/commit/9d2fda15abef318f2d41eeaddef3c2ce0308fb30"><code>9d2fda1</code></a>
Automated Code Change</li>
<li><a
href="https://github.com/google/dagger/commit/592ff20c735968fc62600bb2ac67bf35d3416261"><code>592ff20</code></a>
[XPoet Migration]: Migrate remaining TypeSpec to XTypeSpec.</li>
<li>Additional commits viewable in <a
href="https://github.com/google/dagger/compare/dagger-2.56.1...dagger-2.56.2">compare
view</a></li>
</ul>
</details>
<br />

Updates `com.google.dagger.hilt.android` from 2.56.1 to 2.56.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/google/dagger/releases">com.google.dagger.hilt.android's
releases</a>.</em></p>
<blockquote>
<h2>Dagger 2.56.2</h2>
<h1>Bug fixes</h1>
<ul>
<li>[Dagger] Fixes <a
href="https://redirect.github.com/google/dagger/issues/4676">#4676</a>:
Fixes <code>IndexOutOfBoundException</code> when returning
<code>suspend</code> from <code>@Provides</code> method.
(5d59aedd1)</li>
<li>[Dagger] Fixes <a
href="https://redirect.github.com/google/dagger/issues/4658">#4658</a>:
Fixes <code>NoSuchMethodError</code> due to incorrect Guava runtime
(Dagger’s Guava version is now temporarily pinned to 33.0.0 to avoid the
issue). (9fc3df48e)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/google/dagger/commit/cb98d977e8407363d90eba2fd78a088a1d7640f7"><code>cb98d97</code></a>
2.56.2 release</li>
<li><a
href="https://github.com/google/dagger/commit/96e755c0ef64b7e1c3bd592348d02c562f9d2f26"><code>96e755c</code></a>
[XPoet Migration]: Migrate ParameterSpec to XParameterSpec.</li>
<li><a
href="https://github.com/google/dagger/commit/cccec89061114a97fdbcb566ca2b1da185b15dad"><code>cccec89</code></a>
[XPoet Migration]: Migrate FieldSpec to XPropertySpec.</li>
<li><a
href="https://github.com/google/dagger/commit/5d59aedd1ca559cd42f51fb03c7ed3fa3e3b53dd"><code>5d59aed</code></a>
Disable ad-hoc support for type-use nullability on generated jave type
argume...</li>
<li><a
href="https://github.com/google/dagger/commit/9fc3df48ee8170b4b13366f7b862ecd93bc58471"><code>9fc3df4</code></a>
Pin Guava to version 33.0.0 specified in MODULE.bazel.</li>
<li><a
href="https://github.com/google/dagger/commit/b3ba9b3924bc7fb3fef5efd7abef85018645c58e"><code>b3ba9b3</code></a>
Add maven install lock file.</li>
<li><a
href="https://github.com/google/dagger/commit/7a92bc8b4a87b7ab7c345fd4bf3b6be7c12249db"><code>7a92bc8</code></a>
Internal changes</li>
<li><a
href="https://github.com/google/dagger/commit/dc3a8b32ba3d22666b5fb67b1412cd4100fa12f5"><code>dc3a8b3</code></a>
[XPoet Migration]: Migrate all MethodSpec to XFunSpec.</li>
<li><a
href="https://github.com/google/dagger/commit/9d2fda15abef318f2d41eeaddef3c2ce0308fb30"><code>9d2fda1</code></a>
Automated Code Change</li>
<li><a
href="https://github.com/google/dagger/commit/592ff20c735968fc62600bb2ac67bf35d3416261"><code>592ff20</code></a>
[XPoet Migration]: Migrate remaining TypeSpec to XTypeSpec.</li>
<li>Additional commits viewable in <a
href="https://github.com/google/dagger/compare/dagger-2.56.1...dagger-2.56.2">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>