feat(deps): bump org.jetbrains.kotlinx:kotlinx-serialization-json-okio from 1.5.1 to 1.6.0 (#181)
Bumps
[org.jetbrains.kotlinx:kotlinx-serialization-json-okio](https://github.com/Kotlin/kotlinx.serialization)
from 1.5.1 to 1.6.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/Kotlin/kotlinx.serialization/releases">org.jetbrains.kotlinx:kotlinx-serialization-json-okio's
releases</a>.</em></p>
<blockquote>
<h2>1.6.0</h2>
<p>This release contains all features and bugfixes from <a
href="https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.6.0-RC">1.6.0-RC</a>
plus some bugfixes on its own (see below).
Kotlin 1.9.0 is used as a default, while 1.9.10 is also supported.</p>
<h3>Bugfixes</h3>
<ul>
<li>Improve error messages from Json parser (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2406">#2406</a>)</li>
<li>Mark <code>@SerialName</code>, <code>@Required</code> and
<code>@Transient</code> with <code>@MustBeDocumented</code> (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2407">#2407</a>)</li>
<li>Ensure that no additional files except java compiler output get into
multi-release jar (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2405">#2405</a>)</li>
<li>Fix enums with negative numbers in protobuf not serializing &amp;
de-serializing (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2400">#2400</a>)
(thanks to <a href="https://github.com/Dogacel">Doğaç Eldenk</a>)</li>
</ul>
<h2>1.6.0-RC</h2>
<p>This release is based on the Kotlin 1.9.0.</p>
<h3>Removal of Legacy JS target</h3>
<p>Some time ago, in Kotlin 1.8, <a
href="https://kotlinlang.org/docs/whatsnew18.html#stable-js-ir-compiler-backend">JS
IR compiler was promoted to stable and old JS compiler was
deprecated</a>.
Kotlin 1.9 <a
href="https://kotlinlang.org/docs/whatsnew19.html#removal-of-the-old-kotlin-js-compiler">promotes</a>
the usage of deprecated JS compiler to an error. As a result,
kotlinx.serialization no longer builds with the legacy compiler and does
not distribute artifacts for it. You can read the migration guide for JS
IR compiler <a
href="https://kotlinlang.org/docs/js-ir-migration.html">here</a>.</p>
<p>Also pay attention to the fact that Kotlin/Native also has some <a
href="https://kotlinlang.org/docs/native-target-support.html#deprecated-targets">deprecated
targets</a> that are going to be removed in the Kotlin 1.9.20.
Therefore, kotlinx.serialization 1.6.0-RC and 1.6.0 are likely the last
releases that support these targets.</p>
<h3>Case insensitivity for enums in Json</h3>
<p>This release features a new configuration flag for Json:
<code>decodeEnumsCaseInsensitive</code> that allows you to decode enum
values in a case-insensitive manner.
For example, when decoding <code>enum class Foo { VALUE_A ,
VALUE_B}</code> both inputs <code>&quot;value_a&quot;</code> and
<code>&quot;value_A&quot;</code> will yield <code>Foo.VALUE_A</code>.
You can read more about this feature in the documentation and
corresponding <a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/pull/2345">PR</a>.</p>
<h3>Other bugfixes and enhancements</h3>
<ul>
<li>Add support to decode numeric literals containing an exponent (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2227">#2227</a>)
(thanks to <a href="https://github.com/xBaank">Roberto
Blázquez</a>)</li>
<li>Fix NoSuchMethodError related to Java 8 API compatibility (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2328">#2328</a>,
<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2350">#2350</a>)
(thanks to <a href="https://github.com/Vampire">Björn Kautler</a>)</li>
<li>Changed actual FormatLanguage annotation for JS and Native to avoid
problems with duplicating org.intellij.lang.annotations.Language (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2390">#2390</a>,
<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2379">#2379</a>)</li>
<li>Fix error triggered by 'consume leading class discriminator'
polymorphic parsing optimization (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2362">#2362</a>)</li>
<li>Fix runtime error with Serializer for Nothing on the JS target (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2330">#2330</a>)
(thanks to <a href="https://github.com/ShreckYe">Shreck Ye</a>)</li>
<li>Fix beginStructure in JsonTreeDecoder when inner structure
descriptor is same as outer (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2346">#2346</a>)
(thanks to <a href="https://github.com/ionspin">Ugljesa
Jovanovic</a>)</li>
<li>Actualize 'serializer not found' platform-specific message (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2339">#2339</a>)</li>
<li>Fixed regression with serialization using a list parametrized with
contextual types (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2331">#2331</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/Kotlin/kotlinx.serialization/blob/master/CHANGELOG.md">org.jetbrains.kotlinx:kotlinx-serialization-json-okio's
changelog</a>.</em></p>
<blockquote>
<h1>1.6.0 / 2023-08-22</h1>
<p>This release contains all features and bugfixes from <a
href="https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.6.0-RC">1.6.0-RC</a>
plus some bugfixes on its own (see below).
Kotlin 1.9.0 is used as a default, while 1.9.10 is also supported.</p>
<h3>Bugfixes</h3>
<ul>
<li>Improve error messages from Json parser (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2406">#2406</a>)</li>
<li>Mark <a
href="https://github.com/SerialName"><code>@​SerialName</code></a>, <a
href="https://github.com/Required"><code>@​Required</code></a> and <a
href="https://github.com/Transient"><code>@​Transient</code></a> with <a
href="https://github.com/MustBeDocumented"><code>@​MustBeDocumented</code></a>
(<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2407">#2407</a>)</li>
<li>Ensure that no additional files except java compiler output get into
multi-release jar (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2405">#2405</a>)</li>
<li>Fix enums with negative numbers in protobuf not serializing &amp;
de-serializing (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2400">#2400</a>)
(thanks to <a href="https://github.com/Dogacel">Doğaç Eldenk</a>)</li>
</ul>
<h1>1.6.0-RC / 2023-08-03</h1>
<p>This release is based on the Kotlin 1.9.0.</p>
<h3>Removal of Legacy JS target</h3>
<p>Some time ago, in Kotlin 1.8, <a
href="https://kotlinlang.org/docs/whatsnew18.html#stable-js-ir-compiler-backend">JS
IR compiler was promoted to stable and old JS compiler was
deprecated</a>.
Kotlin 1.9 promotes the usage of deprecated JS compiler to an error. As
a result, kotlinx.serialization no longer builds with the legacy
compiler
and does not distribute artifacts for it. You can read the migration
guide for JS IR compiler <a
href="https://kotlinlang.org/docs/js-ir-migration.html">here</a>.</p>
<p>Also pay attention to the fact that Kotlin/Native also has some <a
href="https://kotlinlang.org/docs/native-target-support.html#deprecated-targets">deprecated
targets</a>
that are going to be removed in the Kotlin 1.9.20. Therefore,
kotlinx.serialization 1.6.0-RC and 1.6.0 are likely the last releases
that support these targets.</p>
<h3>Case insensitivity for enums in Json</h3>
<p>This release features a new configuration flag for Json:
<code>decodeEnumsCaseInsensitive</code>
that allows you to decode enum values in a case-insensitive manner.
For example, when decoding <code>enum class Foo { VALUE_A ,
VALUE_B}</code> both inputs <code>&quot;value_a&quot;</code> and
<code>&quot;value_A&quot;</code> will yield <code>Foo.VALUE_A</code>.
You can read more about this feature in the documentation and
corresponding <a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/pull/2345">PR</a>.</p>
<h3>Other bugfixes and enhancements</h3>
<ul>
<li>Add support to decode numeric literals containing an exponent (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2227">#2227</a>)
(thanks to <a href="https://github.com/xBaank">Roberto
Blázquez</a>)</li>
<li>Fix NoSuchMethodError related to Java 8 API compatibility (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2328">#2328</a>,
<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2350">#2350</a>)
(thanks to <a href="https://github.com/Vampire">Björn Kautler</a>)</li>
<li>Changed actual FormatLanguage annotation for JS and Native to avoid
problems with duplicating org.intellij.lang.annotations.Language (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2390">#2390</a>,
<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2379">#2379</a>)</li>
<li>Fix error triggered by 'consume leading class discriminator'
polymorphic parsing optimization (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2362">#2362</a>)</li>
<li>Fix runtime error with Serializer for Nothing on the JS target (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2330">#2330</a>)
(thanks to <a href="https://github.com/ShreckYe">Shreck Ye</a>)</li>
<li>Fix beginStructure in JsonTreeDecoder when inner structure
descriptor is same as outer (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2346">#2346</a>)
(thanks to <a href="https://github.com/ionspin">Ugljesa
Jovanovic</a>)</li>
<li>Actualize 'serializer not found' platform-specific message (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2339">#2339</a>)</li>
<li>Fixed regression with serialization using a list parametrized with
contextual types (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2331">#2331</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/8baa04b4259274305eea6b02f5c5590b44ea126c"><code>8baa04b</code></a>
Prepare 1.6.0 release (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2414">#2414</a>)</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/79867f12b97e7ea1b8a97b7039f87adca06bf7be"><code>79867f1</code></a>
Merge remote-tracking branch 'origin/master' into dev</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/77af2c971b2ec30140bed3c99c26b8704586dc34"><code>77af2c9</code></a>
Fix incorrect descriptor in advanced JsonDecoder/Encoder example (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2415">#2415</a>)</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/ef923dea2a0fdd5e657a393b8b61f6490b35effb"><code>ef923de</code></a>
Merge remote-tracking branch 'origin/master' into dev</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/a7109d8d0dae37f4b2907b8f3329c79288556d6b"><code>a7109d8</code></a>
Fix negative enums in protobuf not serializing &amp; de-serializing (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2400">#2400</a>)</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/1e88d42f9200da48ec27d0fd066e6bd1923b8b42"><code>1e88d42</code></a>
Rename JsonLexer.kt file to avoid confusion — we do not have this class
anymo...</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/e55f807ac344c5b147075dde924432f6b682642f"><code>e55f807</code></a>
Test &amp; fix several exception messages from Json parser</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/7bf105eb3b730831b14a716786bc50605af6414a"><code>7bf105e</code></a>
Mark <a
href="https://github.com/SerialName"><code>@​SerialName</code></a>, <a
href="https://github.com/Required"><code>@​Required</code></a> and <a
href="https://github.com/Transient"><code>@​Transient</code></a> with <a
href="https://github.com/MustBeDocumented"><code>@​MustBeDocumented</code></a>
(<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2407">#2407</a>)</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/e68f08ed02305fd536abcaf9e289dc72ca105324"><code>e68f08e</code></a>
Use JavaCompile.destinationDirectory instead of the whole task (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2405">#2405</a>)</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/ed1b05707ec27f8864c8b42235b299bdb5e0015c"><code>ed1b057</code></a>
Update Knit to 0.5.0-Beta (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2402">#2402</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/Kotlin/kotlinx.serialization/compare/v1.5.1...v1.6.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.jetbrains.kotlinx:kotlinx-serialization-json-okio&package-manager=gradle&previous-version=1.5.1&new-version=1.6.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>